[package]
name = "vara-app-app"
version = "0.1.0"
edition = "2021"

[dependencies]
vara-sails = { version = "0.7.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = []
